
import React from 'react';
import { 
  Wand2, Palette, Camera, Sticker, Type, ShoppingBag, Film, Scissors, 
  Brush, Layers, PenTool, ScanFace, Globe, FileJson, MessageSquare, Home, UserCircle
} from 'lucide-react';

export const TRANSLATIONS = {
  en: {
    appTitle: "Magic Studio Abi Hisan",
    subtitle: "Pro Creative Suite",
    catGeneral: "General Generation",
    catSpecialized: "Specialized Studio",
    catAdvanced: "Advanced Editing",
    catTools: "Advanced Tools",
    catCollab: "Collaboration",
    menuHome: "Home Dashboard",
    menuTxtImg: "Text to Image",
    menuImgTrans: "Image Transform",
    menuPhoto: "Photorealistic",
    menuRealFace: "Realistic Face Portrait",
    menuSticker: "Sticker & Art",
    menuLogo: "Logo Creator",
    menuProduct: "Product Shot",
    menuComic: "Comic / Storyboard",
    menuSmart: "Smart Editor",
    menuStyle: "Style Transfer",
    menuFashion: "Fashion & Composite",
    menuSketch: "Sketch to Real",
    menuChar: "Character Lab",
    menuLive: "Live Visuals",
    menuRecipe: "Recipe Extractor",
    menuChat: "Creative Chat",
    refImg1: "Reference Image 1",
    refImg2: "Reference Image 2",
    promptLbl: "Prompt Description",
    btnGen: "Generate Image",
    btnTrans: "Transform Image",
    btnDownload: "Download",
    processing: "Processing...",
    rendering: "Rendering...",
    ready: "Ready to Create",
    empty: "Canvas Empty",
    upload: "Upload Image",
    takePhoto: "Take Photo",
    clickUpload: "Click to upload or take photo",
    aspectRatio: "Aspect Ratio",
    quality: "Quality",
    extract: "Extract",
    visualize: "Visualize",
    welcome: "Welcome to",
    heroTitle: "Magic Studio",
    heroSubtitle: "Abi Hisan",
    heroDesc: "Unleash your imagination with the ultimate AI creative suite. Generate, edit, and transform reality.",
    exploreBtn: "Explore Studio",
    featGen: "Generation",
    featEdit: "Editing",
    featTool: "Utility",
    featDesc1: "Create stunning visuals from text.",
    featDesc2: "Modify and transform existing images.",
    featDesc3: "Advanced tools for specific needs.",
    poweredBy: "Powered by Gemini 2.5 and Imagen 4.0",
    footerText: "Developed by Ahmad Hisan, Widyaiswara BDK Denpasar",
    autoPrompt: "Auto-Generate Prompt",
    analyzing: "Analyzing Image...",
    // Style Presets
    styleUltra: "ULTRA-HD DETAIL",
    styleSoft: "SOFT PORTRAIT",
    styleSharp: "SHARP STUDIO",
    styleNatural: "NATURAL DAILY",
    otherStyles: "Choose Other Style Categories",
    official: "OFFICIAL PHOTO",
    pose: "MODEL POSE",
    wedding: "WEDDING",
    business: "BUSINESS",
    cinematic: "CINEMATIC",
    faceMatch: "FACE MATCH ENGINE ACTIVE",
    faceMatchDesc: "Preserving 100% facial identity from reference.",
    magicEnhance: "MAGIC ENHANCE",
    autoOptimize: "AUTO-OPTIMIZE",
    // Categories
    catWedding: "Wedding Styles",
    catOfficial: "Official Photo Styles",
    catModel: "Model Pose Styles",
    catBusiness: "Business Styles",
    catCinematic: "Cinematic Styles",
    // Prompts
    promptTxtImg: "A futuristic city floating in the clouds with waterfalls cascading down, cinematic lighting, 8k resolution.",
    promptImgTrans: "Transform this image into a cyberpunk style with neon lights and rain.",
    promptPhoto: "A photorealistic close-up portrait of an elderly Japanese ceramicist, 85mm lens, soft bokeh, golden hour lighting.",
    promptRealFace: "A high-end realistic portrait of a person with deep expressive eyes, cinematic skin texture, soft shadows.",
    promptSticker: "A kawaii-style sticker of a happy red panda wearing a tiny bamboo hat. Bold clean outlines, white background.",
    promptLogo: "Modern minimalist logo for a coffee shop called 'The Daily Grind'. Clean bold sans-serif, coffee bean icon.",
    promptProduct: "Studio-lit product photo of a minimalist ceramic mug, matte black, on concrete surface, steam rising.",
    promptComic: "3 panel comic in gritty noir style. High contrast black and white inks.",
    promptSmart: "Change only the blue sofa to be a vintage brown leather chesterfield sofa. Keep everything else.",
    promptStyle: "Transform this photograph into the artistic style of Van Gogh's 'Starry Night'.",
    promptFashion: "E-commerce fashion photo. Take the dress from Image 1 and let the model from Image 2 wear it.",
    promptSketch: "Turn this rough pencil sketch of a supercar into a polished photo in a showroom.",
    promptChar: "A studio portrait of this person against a white background, profile looking right.",
    promptLive: "Current global tech trends visualization...",
    promptRecipe: "Ingredients: 2 cups flour, 1 cup sugar..."
  },
  id: {
    appTitle: "Magic Studio Abi Hisan",
    subtitle: "Suite Kreatif Pro",
    catGeneral: "Generasi Umum",
    catSpecialized: "Studio Khusus",
    catAdvanced: "Edit Lanjutan",
    catTools: "Alat Canggih",
    catCollab: "Kolaborasi",
    menuHome: "Beranda Utama",
    menuTxtImg: "Teks ke Gambar",
    menuImgTrans: "Ubah Gambar",
    menuPhoto: "Fotorealistik",
    menuRealFace: "Potret Wajah Realistis",
    menuSticker: "Stiker & Seni",
    menuLogo: "Pembuat Logo",
    menuProduct: "Foto Produk",
    menuComic: "Komik / Storyboard",
    menuSmart: "Editor Cerdas",
    menuStyle: "Transfer Gaya",
    menuFashion: "Fashion & Komposit",
    menuSketch: "Sketsa ke Nyata",
    menuChar: "Lab Karakter",
    menuLive: "Visual Langsung",
    menuRecipe: "Ekstraktor Resep",
    menuChat: "Obrolan Kreatif",
    refImg1: "Gambar Referensi 1",
    refImg2: "Gambar Referensi 2",
    promptLbl: "Deskripsi Prompt",
    btnGen: "Buat Gambar",
    btnTrans: "Ubah Gambar",
    btnDownload: "Unduh",
    processing: "Memproses...",
    rendering: "Merender...",
    ready: "Siap Berkreasi",
    empty: "Kanvas Kosong",
    upload: "Unggah Gambar",
    takePhoto: "Ambil Foto",
    clickUpload: "Klik untuk unggah atau foto",
    aspectRatio: "Rasio Aspek",
    quality: "Kualitas",
    extract: "Ekstrak",
    visualize: "Visualisasikan",
    welcome: "Selamat datang di",
    heroTitle: "Magic Studio",
    heroSubtitle: "Abi Hisan",
    heroDesc: "Bebaskan imajinasimu dengan suite kreatif AI terlengkap. Buat, edit, dan ubah realitas.",
    exploreBtn: "Jelajahi Studio",
    featGen: "Generasi",
    featEdit: "Pengeditan",
    featTool: "Utilitas",
    featDesc1: "Buat visual memukau dari teks.",
    featDesc2: "Ubah dan modifikasi gambar yang ada.",
    featDesc3: "Alat canggih untuk kebutuhan spesifik.",
    poweredBy: "Didukung oleh Gemini 2.5 dan Imagen 4.0",
    footerText: "Dikembangkan oleh Ahmad Hisan, Widyaiswara BDK Denpasar",
    autoPrompt: "Buat Prompt Otomatis",
    analyzing: "Menganalisis Gambar...",
    // Style Presets
    styleUltra: "ULTRA-HD DETAIL",
    styleSoft: "SOFT PORTRAIT",
    styleSharp: "SHARP STUDIO",
    styleNatural: "NATURAL DAILY",
    otherStyles: "Pilih Kategori Gaya Lainnya",
    official: "FOTO RESMI",
    pose: "POSE MODEL",
    wedding: "PERNIKAHAN",
    business: "BISNIS",
    cinematic: "SINEMATIK",
    faceMatch: "FACE MATCH ENGINE ACTIVE",
    faceMatchDesc: "Menjaga 100% identitas wajah dari referensi.",
    magicEnhance: "MAGIC ENHANCE",
    autoOptimize: "AUTO-OPTIMIZE",
    // Categories
    catWedding: "Gaya Pernikahan",
    catOfficial: "Gaya Foto Resmi",
    catModel: "Gaya Pose Model",
    catBusiness: "Gaya Bisnis",
    catCinematic: "Gaya Sinematik",
    // Prompts
    promptTxtImg: "Kota futuristik yang mengapung di awan dengan air terjun, pencahayaan sinematik, resolusi 8k.",
    promptImgTrans: "Ubah gambar ini menjadi gaya cyberpunk dengan lampu neon dan hujan.",
    promptPhoto: "Potret close-up fotorealistik pengrajin keramik Jepang, lensa 85mm, bokeh lembut, cahaya golden hour.",
    promptRealFace: "Potret wajah realistis kelas atas dengan mata ekspresif yang dalam, tekstur kulit sinematik, bayangan lembut.",
    promptSticker: "Stiker gaya kawaii dari panda merah bahagia dengan topi bambu. Garis tepi tebal, latar putih.",
    promptLogo: "Logo minimalis modern untuk kedai kopi 'The Daily Grind'. Font sans-serif tebal, ikon biji kopi.",
    promptProduct: "Foto produk pencahayaan studio cangkir keramik hitam matte di permukaan beton, ada uap.",
    promptComic: "Komik 3 panel gaya noir kasar. Tinta hitam putih kontras tinggi.",
    promptSmart: "Ubah sofa biru menjadi sofa chesterfield kulit cokelat vintage. Sisanya tetap.",
    promptStyle: "Ubah foto ini menjadi gaya artistik 'Starry Night' karya Van Gogh.",
    promptFashion: "Foto mode e-commerce. Ambil baju dari Gambar 1 dan pakaikan ke model di Gambar 2.",
    promptSketch: "Ubah sketsa pensil mobil sport ini menjadi foto mengkilap di showroom.",
    promptChar: "Potret studio orang ini dengan latar putih, profil menghadap ke kanan.",
    promptLive: "Visualisasi tren teknologi global saat ini...",
    promptRecipe: "Bahan: 2 gelas tepung, 1 gelas gula..."
  }
};

export const MENU_ICONS: Record<string, any> = {
  home: Home,
  'text-to-image': Wand2,
  'image-to-image': Palette,
  photorealistic: Camera,
  'photorealistic-portrait': UserCircle,
  'sticker-design': Sticker,
  'logo-creator': Type,
  'product-mockup': ShoppingBag,
  'sequential-art': Film,
  'smart-editor': Scissors,
  'style-transfer': Brush,
  'fashion-composite': Layers,
  'sketch-to-real': PenTool,
  'character-lab': ScanFace,
  'live-visuals': Globe,
  'recipe-extractor': FileJson,
  chat: MessageSquare
};
