
import { GoogleGenAI, Type } from "@google/genai";

export class GeminiService {
  /**
   * Generates images. Uses Gemini 2.5 Flash Image for general tasks
   * and can be extended to Imagen 4.0 if explicitly needed.
   */
  async generateImage(prompt: string, aspectRatio: string = '1:1') {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // Defaulting to Gemini 2.5 Flash Image for better versatility and speed as per guidelines
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts: [{ text: prompt }] },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as any
        }
      }
    });

    const parts = response.candidates?.[0]?.content?.parts || [];
    for (const part of parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by model");
  }

  /**
   * Transforms existing images using Gemini 2.5 Flash Image
   */
  async transformImage(prompt: string, sourceImages: string[]) {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const parts = sourceImages.map(img => ({
      inlineData: {
        data: img.split(',')[1],
        mimeType: img.split(';')[0].split(':')[1]
      }
    }));

    parts.push({ text: prompt } as any);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("Transformation failed to return an image");
  }

  /**
   * Intelligent chat: Uses Gemini 3 for text, switches to 2.5 for image reasoning
   */
  async chat(history: any[]) {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // Check if any message in history contains image data
    const hasImage = history.some(msg => 
      msg.parts.some((p: any) => p.inlineData)
    );

    const model = hasImage ? 'gemini-2.5-flash-image' : 'gemini-3-flash-preview';

    const response = await ai.models.generateContent({
      model,
      contents: history,
      config: {
        thinkingConfig: { thinkingBudget: 0 }
      }
    });

    const parts = response.candidates?.[0]?.content?.parts || [];
    return parts.map(p => {
      if (p.text) return { type: 'text', text: p.text };
      if (p.inlineData) return { type: 'image', url: `data:${p.inlineData.mimeType};base64,${p.inlineData.data}` };
      return null;
    }).filter(Boolean);
  }

  /**
   * Structured data extraction
   */
  async extractRecipe(text: string) {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Extract recipe details from this text: ${text}`,
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            recipe_name: { type: Type.STRING },
            prep_time_minutes: { type: Type.INTEGER },
            ingredients: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  name: { type: Type.STRING },
                  quantity: { type: Type.STRING }
                }
              }
            },
            instructions: { type: Type.ARRAY, items: { type: Type.STRING } }
          }
        }
      }
    });
    return JSON.parse(response.text || '{}');
  }

  /**
   * Google Search Grounding with Visualization
   */
  async getLiveVisuals(prompt: string) {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // Step 1: Search grounding
    const searchRes = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Search Google for current info about: "${prompt}". Summarize and then write an image prompt starting with 'IMAGE_PROMPT: '.`,
      config: {
        tools: [{ googleSearch: {} }]
      }
    });

    const text = searchRes.text || "";
    const splitIndex = text.indexOf("IMAGE_PROMPT:");
    const summary = splitIndex > -1 ? text.substring(0, splitIndex).trim() : text;
    const imgPrompt = splitIndex > -1 ? text.substring(splitIndex + 13).trim() : prompt;

    // Step 2: Visualization
    const imgUrl = await this.generateImage(imgPrompt, '16:9');

    return {
      summary,
      imageUrl: imgUrl,
      grounding: searchRes.candidates?.[0]?.groundingMetadata
    };
  }
}

export const gemini = new GeminiService();
